# Generated by Django 4.1.5 on 2023-01-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Curriculum",
                "verbose_name_plural": "Curriculums",
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "question_paper",
                    models.FileField(upload_to="question_papers/"),
                ),
                ("mark_scheme", models.FileField(upload_to="mark_schemes/")),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum",
                        to="api.curriculum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paper",
                "verbose_name_plural": "Papers",
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Qualification",
                "verbose_name_plural": "Qualifications",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "curriculums",
                    models.ManyToManyField(
                        related_name="curriculums", to="api.curriculum"
                    ),
                ),
                (
                    "papers",
                    models.ManyToManyField(
                        blank=True, related_name="papers", to="api.paper"
                    ),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(
                        related_name="qualifications", to="api.qualification"
                    ),
                ),
                (
                    "sessions",
                    models.ManyToManyField(
                        blank=True, related_name="sessions", to="api.session"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.AddField(
            model_name="paper",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualification",
                to="api.qualification",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="api.session",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject",
                to="api.subject",
            ),
        ),
    ]
