# Generated by Django 4.1.2 on 2022-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
            },
        ),
        migrations.AlterField(
            model_name="subject",
            name="curriculums",
            field=models.ManyToManyField(
                related_name="curriculums", to="subjects.curriculum"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="qualifications",
            field=models.ManyToManyField(
                related_name="qualifications", to="subjects.qualification"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="sessions",
            field=models.ManyToManyField(
                related_name="sessions", to="subjects.session"
            ),
        ),
    ]
