# Generated by Django 4.1.2 on 2022-10-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="subjects.session",
            ),
            preserve_default=False,
        ),
    ]
