# Generated by Django 4.1.2 on 2022-10-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0004_paper_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="curriculum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculum",
                to="subjects.curriculum",
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualification",
                to="subjects.qualification",
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="subjects.session",
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject",
                to="subjects.subject",
            ),
        ),
    ]
