# Generated by Django 4.1.2 on 2022-10-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subjects",
            "0005_alter_paper_curriculum_alter_paper_qualification_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="subject",
        ),
        migrations.AddField(
            model_name="subject",
            name="papers",
            field=models.ManyToManyField(
                related_name="papers", to="subjects.paper"
            ),
        ),
    ]
