# Generated by Django 4.1.2 on 2022-10-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0008_remove_subject_papers"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="papers",
            field=models.ManyToManyField(
                related_name="papers", to="subjects.paper"
            ),
        ),
    ]
