# Generated by Django 4.1.2 on 2022-10-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0009_subject_papers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="papers",
            field=models.ManyToManyField(
                blank=True, related_name="papers", to="subjects.paper"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="sessions",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="subjects.session"
            ),
        ),
    ]
