# Generated by Django 4.1.3 on 2022-11-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0011_paper_mark_scheme_paper_question_paper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="ms_url",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="qp_url",
        ),
    ]
