# Generated by Django 4.1.3 on 2022-11-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0012_remove_paper_ms_url_remove_paper_qp_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="mark_scheme",
            field=models.FileField(upload_to="mark_schemes/"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="question_paper",
            field=models.FileField(upload_to="question_papers/"),
        ),
    ]
